// User reducer types
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";
export const LOADED_USER = "LOADED_USER";
// UI reducer types
export const LOADING_UI = "LOADING_UI";
export const SET_ERRORS = "SET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_ALERTS = "SET_ALERTS";
export const CLEAR_ALERTS = "CLEAR_ALERTS";
// Data reducer types
export const LOADING_DATA = "LOADING_DATA";
export const SET_DOCTORS = "SET_DOCTORS";
export const SET_DOCTOR = "SET_DOCTOR";

export const userActionTypes = {
    SAVE_USER: "SAVE_USER",
    SET_USER: "SET_USER",
    SET_AUTHENTICATED: "SET_AUTHENTICATED",
    SET_UNAUTHENTICATED: "SET_UNAUTHENTICATED",
}
export const uiActionTypes = {
    START_ACTION: "START_ACTION",
    STOP_ACTION: "STOP_ACTION",
    REFRESH_ACTION_START: "REFRESH_ACTION_START",
    REFRESH_ACTION_STOP: "REFRESH_ACTION_STOP",
    SET_ERROR: "SET_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR"
};
export const doctorsActionTypes = {
    GET_DOCTORS: "GET_DOCTORS",
    GET_DOCTORS_DONE: "GET_DOCTORS_DONE",
    GET_DOCTORS_ERROR: "GET_DOCTORS_ERROR",
    UPDATE_DOCTORS: "UPDATE_DOCTORS",
    UPDATE_DOCTORS_DONE: "UPDATE_DOCTORS_DONE",
    UPDATE_DOCTORS_ERROR: "UPDATE_DOCTORS_ERROR"
};
export const doctorActionTypes = {
    SET_DOCTOR: "SET_DOCTOR",
    SET_DOCTOR_DONE: "SET_DOCTOR_DONE",
    SET_DOCTOR_ERROR: "SET_DOCTOR_ERROR",
    SET_APPOINTMENT: "SET_APPOINTMENT",
    SET_APPOINTMENT_DONE: "SET_APPOINTMENT_DONE",
    SET_APPOINTMENT_ERROR: "SET_APPOINTMENT_ERROR"
};